// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BxBxsChevronLeft: typeof import('~icons/bx/bxs-chevron-left')['default']
    BxBxsChevronRight: typeof import('~icons/bx/bxs-chevron-right')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    LoaderPokemonList: typeof import('./components/loader/LoaderPokemonList.vue')['default']
    LoaderPokemonListItem: typeof import('./components/loader/LoaderPokemonListItem.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    PokemonDetailModal: typeof import('./components/pokemon/PokemonDetailModal.vue')['default']
    PokemonList: typeof import('./components/pokemon/PokemonList.vue')['default']
    PokemonListItem: typeof import('./components/pokemon/PokemonListItem.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
